spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  h2:
    console.enabled: false
