CREATE TABLE if not exists users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar,
    lastName varchar,
    age      int
);

CREATE TABLE if not exists orders
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar,
    status      varchar
);
